obstacle_range: 2.5 # the robot will only update its map with information about obstacles that are within 2.5 meters 
raytrace_range: 3.0 # means that the robot will attempt to clear out space in front of it up to 3.0 meters 
# footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
robot_radius: 0.0855
inflation_radius: 0.55

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: head, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

# point_cloud_sensor: {sensor_frame: head, data_type: PointCloud, topic: /particlecloud, marking: true, clearing: true}