### mission params ###
mission:
  # waypoint units in [[m], [m], [rad]]
  waypoints: [[2.0, 0.0], [3.0, 4.0], [3.0, 7.0],
              [7.0, 7.0], [7.0, 11.0]]
  distance_margin: 0.15   # [m]
### controller params ###
controller:
  # controller gains
  Kp: [1.0, 1.0]  # proportional gains [linear, angular]
  Kd: [1.0, 1.0]  # derivative gains [linear, angular]
